/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;

import static cms.Home.abc;
import static cms.Medication.lbl_id;
import static cms.Medication.txt_fullname;
import cms.function.SQLConnection;
import static cms.function.Uppercase.uppercase;
import com.sun.glass.events.KeyEvent;
import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjie
 */
public class add_med extends javax.swing.JDialog {

    Connection conn = SQLConnection.ConnDB();
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    Date helloworld = new Date();
    public add_med() {
        initComponents();
        lbl_name.setText(txt_fullname.getText());
        idsheet.setText(lbl_id.getText());
        
        JTextFieldDateEditor editor_birth = (JTextFieldDateEditor) date_last_attack.getDateEditor();
        editor_birth.setEditable(false);
        
        date_last_attack.setMaxSelectableDate(helloworld);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        txt_present_ill = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        date_last_attack = new com.toedter.calendar.JDateChooser();
        jLabel51 = new javax.swing.JLabel();
        txt_maintenance = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        idsheet = new javax.swing.JLabel();

        setModal(true);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 61, 115)));

        jPanel5.setBackground(new java.awt.Color(10, 61, 115));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Add Medical Problem");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(120, 120, 120));
        jLabel49.setText("Illness Name");

        txt_present_ill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_present_ill.setForeground(new java.awt.Color(46, 47, 51));
        txt_present_ill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_present_illKeyTyped(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(120, 120, 120));
        jLabel50.setText("Last Attack");

        date_last_attack.setDateFormatString("YYYY-MM-dd");
        date_last_attack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date_last_attack.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                date_last_attackComponentAdded(evt);
            }
        });
        date_last_attack.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_last_attackFocusLost(evt);
            }
        });
        date_last_attack.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                date_last_attackInputMethodTextChanged(evt);
            }
        });
        date_last_attack.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date_last_attackPropertyChange(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(120, 120, 120));
        jLabel51.setText("Maintenance Medications");

        txt_maintenance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_maintenance.setForeground(new java.awt.Color(46, 47, 51));
        txt_maintenance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_maintenanceKeyTyped(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("Cancel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_name.setText("Name");

        idsheet.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        idsheet.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idsheet, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_maintenance)
                            .addComponent(txt_present_ill)
                            .addComponent(date_last_attack, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(lbl_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idsheet)
                .addGap(18, 18, 18)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_present_ill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_last_attack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_maintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(0, 48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_present_illKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_present_illKeyTyped
        char c = evt.getKeyChar();
        
        if (!(Character.isAlphabetic(c) ||
            (Character.isDigit(c)) ||   
            (c==KeyEvent.VK_BACKSPACE) ||
            (c==KeyEvent.VK_PERIOD) ||
            (c==KeyEvent.VK_COMMA) ||   
            (c==KeyEvent.VK_SPACE) ||
            (c==KeyEvent.VK_DELETE))){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null, "Invalid Character", "WARNING!", JOptionPane.WARNING_MESSAGE);

        }
        
        uppercase(txt_present_ill);
    }//GEN-LAST:event_txt_present_illKeyTyped

    private void date_last_attackComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_date_last_attackComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_date_last_attackComponentAdded

    private void date_last_attackFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_last_attackFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_date_last_attackFocusLost

    private void date_last_attackInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_date_last_attackInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_date_last_attackInputMethodTextChanged

    private void date_last_attackPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date_last_attackPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_date_last_attackPropertyChange

    private void txt_maintenanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_maintenanceKeyTyped
        char c = evt.getKeyChar();
        
        if (!(Character.isAlphabetic(c) ||
            (Character.isDigit(c)) ||   
            (c==KeyEvent.VK_BACKSPACE) ||
            (c==KeyEvent.VK_PERIOD) ||
            (c==KeyEvent.VK_COMMA) ||   
            (c==KeyEvent.VK_SPACE) ||
            (c==KeyEvent.VK_DELETE))){
        getToolkit().beep();
        evt.consume();
        JOptionPane.showMessageDialog(null, "Invalid Character", "WARNING!", JOptionPane.WARNING_MESSAGE);

        }
        
        uppercase(txt_maintenance);
    }//GEN-LAST:event_txt_maintenanceKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (txt_present_ill.getText().isEmpty() || date_last_attack.getDateFormatString().isEmpty() || txt_maintenance.getText().isEmpty()){

            JOptionPane.showMessageDialog(null, "Please complete all textfields");
            txt_present_ill.setText("");
            date_last_attack.setDate(null);
            txt_maintenance.setText("");
        }else{

            String present, petsa, maintenance;

            present = txt_present_ill.getText();
            petsa = abc.format(date_last_attack.getDate());
            maintenance = txt_maintenance.getText();

            try{
                String query = "INSERT INTO med_problem SET"
                        + " id_no = '"+idsheet.getText()+"',"
                        + " active_ill = '"+present+"',"
                        + " lastattack = '"+petsa+"',"
                        + " maintenance = '"+maintenance+"'";
                pstmt = conn.prepareStatement(query);
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Successfully Added");
                this.dispose();
                Medication p = new Medication();
                p.lbl_id.setText(idsheet.getText());
                p.setVisible(true);
            }catch(Exception e){
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
        Medication p = new Medication();
        p.lbl_id.setText(idsheet.getText());
        p.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_med().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date_last_attack;
    private javax.swing.JLabel idsheet;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JTextField txt_maintenance;
    private javax.swing.JTextField txt_present_ill;
    // End of variables declaration//GEN-END:variables
}
