/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;

import static cms.Medication.lbl_id;
import static cms.Medication.txt_fullname;
import static cms.Medication.txt_progyear;

import cms.function.ExcelExporter;
import static cms.function.Loginfunction.Firstname;
import static cms.function.Loginfunction.Lastname;
import cms.function.SQLConnection;
import static cms.function.tbl_function.tbl_function;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;

/**
 *
 * @author Benjie
 */
public class all_transaction extends javax.swing.JDialog {
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    Connection conn = SQLConnection.ConnDB();

    /**
     * Creates new form all_transaction
     */
    public all_transaction() {
        initComponents();
        tbl_function(tbl_transaction);
        
        lbl_idko.setText(lbl_id.getText());
        lbl_name.setText(txt_fullname.getText());
        lbl_prog.setText(txt_progyear.getText());
        
        
        
    }
    
    public void transactions(){
        try{
        DefaultTableModel mod = (DefaultTableModel)tbl_transaction.getModel();
        mod.setRowCount(0);
String q = "SELECT DATE_FORMAT(date_given, '%M %e, %Y') as 'Date', TIME_FORMAT(time, '%h:%i %p') AS 'Time', a.bedrest as 'bedrest',"
                    + " c.ill_name as illname, b.med_name as medname, TIME_FORMAT(TIMEDIFF(a.outtime, a.intime), '%h') as a, TIME_FORMAT(TIMEDIFF(a.outtime, a.intime), '%i') as b, a.outTime"
                    + " FROM med_dspnsd a INNER JOIN med_table b ON a.med_id = b.med_id"
                    + " INNER JOIN ill_table c ON a.ill_id = c.ill_id"
                    + " WHERE id_no = '"+lbl_id.getText()+"'"
                    + " ORDER BY date_given DESC, time DESC;";
            
            String p;
            pstmt = conn.prepareStatement(q);
            rs = pstmt.executeQuery();
             while (rs.next()){
                String ab = rs.getString("Date");
                String cd = rs.getString("Time");
                String ef = rs.getString("illname");
                String gh = rs.getString("medname");
                int ij = rs.getInt("bedrest");
                int in = rs.getInt("a");
                int in2 = rs.getInt("b");
                Date check = rs.getDate("a.outtime");
                
                if (ij==0){
                    p = "No";
                }else{
                    
                    if (check == null){
                        p = "Yes"+"; Ongoing";
                    }else{
                        p = "Yes"+"; "+in+" hours & "+in2+" minutes";
                    }
                    
                }

                Object karga [] = {ab,cd,ef,gh,p};
                mod.addRow(karga);
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_transaction = new javax.swing.JTable();
        lbl_idko = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_export = new javax.swing.JButton();
        lbl_prog = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 61, 115)));

        tbl_transaction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Illness", "Medicine Given", "Bedrest"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_transaction.setColumnSelectionAllowed(true);
        tbl_transaction.setRowHeight(30);
        tbl_transaction.setRowMargin(2);
        tbl_transaction.setShowHorizontalLines(false);
        tbl_transaction.setShowVerticalLines(false);
        tbl_transaction.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_transaction);
        tbl_transaction.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lbl_idko.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_idko.setForeground(new java.awt.Color(10, 61, 115));
        lbl_idko.setText("10000202952");

        lbl_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(10, 61, 115));
        lbl_name.setText("Transactions");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_export.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_export.setText("Export");
        btn_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportActionPerformed(evt);
            }
        });

        lbl_prog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_prog.setForeground(new java.awt.Color(10, 61, 115));
        lbl_prog.setText("Transactions");

        jPanel2.setBackground(new java.awt.Color(10, 61, 115));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Transactions");

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_export, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_idko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_prog, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_idko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_prog)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btn_export))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        transactions();
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel) tbl_transaction.getModel();
        JRTableModelDataSource  datasource = new JRTableModelDataSource(mod);
        String reportSource = "C:\\Users\\Benjie\\Desktop\\PROGRAM FILE THESIS 2015-2016\\CMS\\CMS\\src\\reports\\studentTrans.jrxml";
        
        int x = mod.getRowCount();
        
        String name = lbl_name.getText();
        String id = lbl_idko.getText();
        String prog = lbl_prog.getText();
        
        String nurseName = Firstname +" "+ Lastname;

        if (x == 0){
                JOptionPane.showMessageDialog(this, "No result to be print");
        }else{
            try {
                JasperReport jr =  JasperCompileManager.compileReport(reportSource);
                Map<String, Object> params = new HashMap<String, Object>();
                params.put("name", name);
                params.put("id", id);
                params.put("prog", prog);
                params.put("nurseName", nurseName);
                JasperPrint jp = JasperFillManager.fillReport(jr, params, datasource);
                JasperPrintManager.printReport(jp, false);

                JasperExportManager.exportReportToPdfFile(jp,"report.pdf");
                if (Desktop.isDesktopSupported()) {
                    try {
                        File myFile = new File("report.pdf");
                        Desktop.getDesktop().open(myFile);
                    } catch (IOException ex) {
                        // no application registered for PDFs
                    }
                }

            } catch (JRException ex) {
                ex.printStackTrace();
            }
        }
//        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportActionPerformed
        try {
                ExcelExporter exp = new ExcelExporter();
                exp.exportTable(tbl_transaction, new File ("C:/Users/Benjie/Desktop/'"+lbl_idko.getText()+"'.xls"));
                JOptionPane.showMessageDialog(this, "You have sucsessfully export the data to Excel, Please check the file on the computer");  
            } catch (IOException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btn_exportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new all_transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_export;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lbl_idko;
    public static javax.swing.JLabel lbl_name;
    public static javax.swing.JLabel lbl_prog;
    private javax.swing.JTable tbl_transaction;
    // End of variables declaration//GEN-END:variables
}
