/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;


import static cms.function.Loginfunction.Firstname;
import static cms.function.Loginfunction.Lastname;
import cms.function.SQLConnection;
import static cms.function.tbl_function.tbl_function;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang.WordUtils;

/**
 *
 * @author Benjie
 */
public class frm_sendNotif extends javax.swing.JFrame {
    
    
    

    /**
     * Creates new form frm_sendNotif
     */
    Connection conn = SQLConnection.ConnDB();
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    Statement st = null;
    
    public static String transDate = "";
    public static String transTime = "";
    public static String ill = "";
    public static String medGiven = "";
    public static String bedRest = "";
    public static String patientName = "";
    
    String finalEmail = "";
    String empName = "";
    
    public frm_sendNotif() {
        
        
        initComponents();
        tbl_function(emp_table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(10, 61, 115));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Email Notification");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(10, 61, 115)));
        jPanel2.setForeground(new java.awt.Color(10, 61, 115));

        emp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Position", "Check"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        emp_table.setRowHeight(27);
        emp_table.setRowMargin(2);
        emp_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(emp_table);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*Please Select a employee you want to notify");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Send Now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Search :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        showEmployees();
        
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int dialogresult = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Send a notification on the selected employees ? ", "", JOptionPane.YES_OPTION);;    
        if (dialogresult == 0){
             for (int i = 0; i<emp_table.getRowCount();i++){
                Boolean Checked = Boolean.valueOf(emp_table.getValueAt(i,4).toString());{
                if (Checked == true){
                    finalEmail = emp_table.getValueAt(i,2).toString();
                    empName = emp_table.getValueAt(i,1).toString();
                    sendpwtoemail();
                    //System.out.println(finalEmail);
                    JOptionPane.showMessageDialog(null, "You have Successfully send a notification on the selected employees");
                    }         
                }
            } 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        try{
            DefaultTableModel mod = (DefaultTableModel)emp_table.getModel();
            mod.setRowCount(0);
            
            String q = "SELECT * FROM patient_tbl WHERE Occupation = 'Employee' AND (id_no LIKE '%"+txt_search.getText()+"%' OR lastname LIKE '%"+txt_search.getText()+"%'"
                    + " OR firstname LIKE '%"+txt_search.getText()+"%' OR middlename LIKE '%"+txt_search.getText()+"%')";
            pstmt = conn.prepareStatement(q);
            rs = pstmt.executeQuery();
            while (rs.next()){
                String id = rs.getString("id_no");
                String l = rs.getString("lastname");
                String f = rs.getString("firstname");
                String m = WordUtils.capitalizeFully(WordUtils.initials(rs.getString("middlename")));
                String k = rs.getString("Occupation");
                String full = l + ", "+f+" "+m+".";
                Boolean x = false;
                
                //Creation OF AUTO GENERATED EMAIL NG STI
                 String unaName = f.toLowerCase().replaceAll(" ", "."); //removing space on firstname and replace space to dot
                String unaNameFinal = unaName.replaceAll("ñ", "n"); //replacing ñ on firstname and replace space to n
                //System.out.println(replace_enye_fname);

                String huliName = l.toLowerCase().replaceAll(" ", ""); //removing space on lastname
                String huliNameFinal = huliName.replaceAll("ñ", "n"); //replacing ñ on lastname and replace space to n
                //System.out.print(replace_enye_lname);

                String huliEmail = unaNameFinal+"."+huliNameFinal+"@globalcity.sti.edu";
                
                
                
                mod.addRow(new Object[]{id,full,huliEmail,k,x});
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_searchKeyTyped
    
    public void sendpwtoemail(){
        
        
        
        String emailsubject = "STI College Clinic Patient Transaction Notification";
        //String bodymsg = "Test Lang";
        String bodymsg = "Goodday "+ empName +",\n\n      This is to certify that Mr./Ms. "+patientName+" has been confined/held in the school clinic last "+transDate+ "/"+transTime+
                ". He/She suffered "+ill+" and has been given a "+medGiven+"  as a medication.                \n\n\n\n\n\n Best Regards, \n\n"+Firstname+" "+Lastname+"\nADMINISTRATOR";
        
        final String username = "clinic.stiglobal@gmail.com";
        final String pass = "Password1234@@";

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable","true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session sesh = Session.getInstance(props,
            new javax.mail.Authenticator(){
                @Override
                protected PasswordAuthentication getPasswordAuthentication(){
                    return new PasswordAuthentication(username, pass);

                    //return sesh;

                }
            });
            try{
                Message msg = new MimeMessage(sesh);
                msg.setFrom(new InternetAddress("clinic.stiglobal@gmail.com"));
                msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(finalEmail));
                msg.setSubject(emailsubject);
                msg.setText(bodymsg);

                Transport.send(msg);
                System.out.println("SUCCESS YES NAG SEND KA RIN");
                //JOptionPane.showMessageDialog(this, "NAG SEND NA");
            }catch(MessagingException e){
                throw new RuntimeException(e);
            }
    }
    
    public void showEmployees(){
        
        DefaultTableModel model = (DefaultTableModel)emp_table.getModel();
        model.getDataVector().removeAllElements();
        emp_table.repaint();
        //String nurse = "Nurse";
        try {
            st = conn.createStatement();
            String query = "SELECT * FROM patient_tbl WHERE occupation = 'Employee';";
            rs = st.executeQuery(query);

            while (rs.next()){
                String id_no = rs.getString("id_no");
                String lastname = rs.getString("lastname");
                String firstname = rs.getString("firstname");
                String middlename = rs.getString("middlename");
                String occupation = rs.getString("occupation");
                
                
                String unaName = firstname.toLowerCase().replaceAll(" ", "."); //removing space on firstname and replace space to dot
                String unaNameFinal = unaName.replaceAll("ñ", "n"); //replacing ñ on firstname and replace space to n
                //System.out.println(replace_enye_fname);

                String huliName = lastname.toLowerCase().replaceAll(" ", ""); //removing space on lastname
                String huliNameFinal = huliName.replaceAll("ñ", "n"); //replacing ñ on lastname and replace space to n
                //System.out.print(replace_enye_lname);

                String huliEmail = unaNameFinal+"."+huliNameFinal+"@globalcity.sti.edu";
               // System.out.println(huliEmail);
                
                
                
                String capfname = WordUtils.capitalizeFully(firstname);
                String capmname = WordUtils.capitalizeFully(middlename);
                String caplname = WordUtils.capitalizeFully(lastname);
                Boolean x = false;
                model.addRow(new Object[]{id_no, capfname+" "+capmname+" "+caplname,huliEmail, occupation,x});
                //getTable();
            }
            //System.out.println("SUCSESS GAGO");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "showEmployees");
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_sendNotif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_sendNotif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_sendNotif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_sendNotif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_sendNotif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable emp_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
