/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;

import static cms.function.Loginfunction.Firstname;
import static cms.function.Loginfunction.Lastname;
import static cms.function.Loginfunction.user_ID;
import cms.function.SQLConnection;
import static cms.function.tbl_function.tbl_function;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Benjie
 */
public class frm_purchase extends javax.swing.JFrame {

    /**
     * Creates new form frm_purchase
     */
    Connection conn = SQLConnection.ConnDB();
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    Statement st = null;
    Date max_date = new Date();
    public static SimpleDateFormat abc = new SimpleDateFormat("YYYY-MM-dd");
    public static LocalDate nowna = LocalDate.now();
    
    
    public frm_purchase() {
        initComponents();
        tbl_function(order_table);
        Calendar cal = Calendar.getInstance();
        cal.getTime();
        txt_date.setText(abc.format(cal.getTime()));
        txt_supid3.setText(Firstname +" "+ Lastname);
        countPO();
        showSuplist();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        order_table = new javax.swing.JTable();
        Navigation1 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_medical1 = new javax.swing.JLabel();
        tgl_genOrder = new javax.swing.JToggleButton();
        tgl_basic2 = new javax.swing.JToggleButton();
        tgl_contact2 = new javax.swing.JToggleButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_poid = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txt_supid3 = new javax.swing.JTextField();
        cmbSup = new javax.swing.JComboBox();
        checkbox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(10, 61, 115));
        jPanel2.setPreferredSize(new java.awt.Dimension(1299, 96));

        jLabel45.setFont(new java.awt.Font("Arcon", 0, 30)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Purchase Order");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 61, 115)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1407, 659));

        order_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine ID", "Name", "Remaining Quantity", "Quantity", "Remove"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        order_table.setRowHeight(25);
        order_table.setShowHorizontalLines(false);
        order_table.setShowVerticalLines(false);
        jScrollPane1.setViewportView(order_table);

        Navigation1.setBackground(new java.awt.Color(10, 61, 115));
        Navigation1.setPreferredSize(new java.awt.Dimension(319, 334));

        jSeparator5.setBackground(new java.awt.Color(10, 61, 115));

        lbl_medical1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lbl_medical1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_medical1.setText("Options");

        tgl_genOrder.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tgl_genOrder.setForeground(new java.awt.Color(193, 195, 198));
        tgl_genOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/contact_1.png"))); // NOI18N
        tgl_genOrder.setText("   Generate Order");
        tgl_genOrder.setBorderPainted(false);
        tgl_genOrder.setContentAreaFilled(false);
        tgl_genOrder.setFocusPainted(false);
        tgl_genOrder.setFocusable(false);
        tgl_genOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tgl_genOrder.setIconTextGap(6);
        tgl_genOrder.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/contact_2.png"))); // NOI18N
        tgl_genOrder.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/contact_2.png"))); // NOI18N
        tgl_genOrder.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/contact_2.png"))); // NOI18N
        tgl_genOrder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tgl_genOrderItemStateChanged(evt);
            }
        });
        tgl_genOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tgl_genOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tgl_genOrderMouseExited(evt);
            }
        });
        tgl_genOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_genOrderActionPerformed(evt);
            }
        });

        tgl_basic2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tgl_basic2.setForeground(new java.awt.Color(255, 255, 255));
        tgl_basic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/info_1.png"))); // NOI18N
        tgl_basic2.setText("   Browse Medicine");
        tgl_basic2.setBorderPainted(false);
        tgl_basic2.setContentAreaFilled(false);
        tgl_basic2.setFocusPainted(false);
        tgl_basic2.setFocusable(false);
        tgl_basic2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tgl_basic2.setIconTextGap(6);
        tgl_basic2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/info_2.png"))); // NOI18N
        tgl_basic2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/info_2.png"))); // NOI18N
        tgl_basic2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/info_2.png"))); // NOI18N
        tgl_basic2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tgl_basic2ItemStateChanged(evt);
            }
        });
        tgl_basic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tgl_basic2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tgl_basic2MouseExited(evt);
            }
        });
        tgl_basic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_basic2ActionPerformed(evt);
            }
        });

        tgl_contact2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tgl_contact2.setForeground(new java.awt.Color(193, 195, 198));
        tgl_contact2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/contact_1.png"))); // NOI18N
        tgl_contact2.setText("   Abort");
        tgl_contact2.setBorderPainted(false);
        tgl_contact2.setContentAreaFilled(false);
        tgl_contact2.setFocusPainted(false);
        tgl_contact2.setFocusable(false);
        tgl_contact2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        tgl_contact2.setIconTextGap(6);
        tgl_contact2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/contact_2.png"))); // NOI18N
        tgl_contact2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/contact_2.png"))); // NOI18N
        tgl_contact2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registration/contact_2.png"))); // NOI18N
        tgl_contact2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tgl_contact2ItemStateChanged(evt);
            }
        });
        tgl_contact2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tgl_contact2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tgl_contact2MouseExited(evt);
            }
        });
        tgl_contact2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_contact2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Navigation1Layout = new javax.swing.GroupLayout(Navigation1);
        Navigation1.setLayout(Navigation1Layout);
        Navigation1Layout.setHorizontalGroup(
            Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navigation1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Navigation1Layout.createSequentialGroup()
                        .addGroup(Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_medical1)
                            .addComponent(jSeparator5))
                        .addContainerGap())
                    .addGroup(Navigation1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl_basic2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(tgl_genOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tgl_contact2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        Navigation1Layout.setVerticalGroup(
            Navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Navigation1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_medical1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tgl_basic2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl_genOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgl_contact2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(120, 120, 120));
        jLabel43.setText("Choose Supplier");

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(120, 120, 120));
        jLabel44.setText("Purchase Order Number");

        txt_poid.setEditable(false);
        txt_poid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_poid.setForeground(new java.awt.Color(10, 61, 115));
        txt_poid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_poidKeyTyped(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(120, 120, 120));
        jLabel46.setText("Created Date");

        txt_date.setEditable(false);
        txt_date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_date.setForeground(new java.awt.Color(10, 61, 115));
        txt_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dateKeyTyped(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(120, 120, 120));
        jLabel47.setText("Prepared by");

        txt_supid3.setEditable(false);
        txt_supid3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_supid3.setForeground(new java.awt.Color(10, 61, 115));
        txt_supid3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_supid3KeyTyped(evt);
            }
        });

        cmbSup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        checkbox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkbox1.setText("Select All");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Remove Checked");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(Navigation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(342, 342, 342))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(cmbSup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(176, 176, 176)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_supid3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_poid, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 105, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Navigation1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_poid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSup, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_supid3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkbox1)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1407, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        
    }//GEN-LAST:event_formWindowActivated
    
     public void countPO(){

        try {
            st = conn.createStatement();
            String query = "SELECT COUNT(po_id) as a FROM purchase_orders;";
            rs = st.executeQuery(query);
            
            while (rs.next()){
                String count = rs.getString("a");
                int countFinal = Integer.parseInt(count)+1;
                txt_poid.setText("PO-"+Integer.toString(countFinal));
                
            }
            
            //System.out.println("SUCSESS GAGO");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "hello");
        }

    }
    
    public void showSuplist(){
        //userlist
       
        try {
            st = conn.createStatement();
            String query = "SELECT * FROM supplier;";
            rs = st.executeQuery(query);

            while (rs.next()){
                String sup_id = rs.getString("sup_id");
                String sup_name = rs.getString("sup_name");
                String sup_add = rs.getString("sup_add");
                
                cmbSup.addItem(sup_name);
                //getTable();
                
            }
            //System.out.println("SUCSESS GAGO");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "updateTable");
        }

    } 
     
    private void tgl_genOrderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tgl_genOrderItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_genOrderItemStateChanged

    private void tgl_genOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgl_genOrderMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_genOrderMouseEntered

    private void tgl_genOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgl_genOrderMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_genOrderMouseExited

    private void tgl_genOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_genOrderActionPerformed
        int dialogresult = JOptionPane.showConfirmDialog(rootPane, "To generate the Purchase order click Yes to proceed", "Hello Print", JOptionPane.YES_OPTION);;
            if (dialogresult == 0){
                generateOrder();       
            }
    }//GEN-LAST:event_tgl_genOrderActionPerformed
    
    public void generateOrder(){
        
        String supp = cmbSup.getSelectedItem().toString();
        int row = order_table.getRowCount();
        if (row == 0){
            JOptionPane.showMessageDialog(this, "Please browse medicine to be ordered ?");                    
        } else {
            
                try {
                    String sql = "INSERT INTO purchase_orders SET"
                            + " po_id = '"+txt_poid.getText()+"',"
                            + " po_sup = '"+supp+"',"
                            + " po_date = '"+nowna+"',"
                            + " po_ship = '"+nowna+"',"
                            + " po_prepby = '"+user_ID+"',"
                            + " po_status = 'PENDING';";
                    st = conn.prepareStatement(sql);
                    st.executeUpdate(sql);
                    //System.out.println("D@");

                    for (int i = 0; i!=row;i++){
                        String med_id = (order_table.getModel().getValueAt(i, 0).toString());
                        String qnty = (order_table.getModel().getValueAt(i, 3).toString());
                        String insertOrders = "INSERT INTO med_orders SET" 
                                + " po_order = '"+txt_poid.getText()+"'"
                                + ", med_id = '"+med_id+"'"
                                + ", med_qnty = '"+qnty+"';";
                        st = conn.prepareStatement(insertOrders);
                        st.executeUpdate(insertOrders);
                    }
                    JOptionPane.showMessageDialog(this, "You have sucsessfully Generated the Purchase Order Number: "+txt_poid.getText());
                    dispose();
                    //dispose();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "generateOrder");
                    e.printStackTrace();
                }  

        }
        
    }
    
    private void tgl_basic2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tgl_basic2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_basic2ItemStateChanged

    private void tgl_basic2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgl_basic2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_basic2MouseEntered

    private void tgl_basic2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgl_basic2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_basic2MouseExited

    private void tgl_basic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_basic2ActionPerformed
        new frm_result_med().setVisible(true);
    }//GEN-LAST:event_tgl_basic2ActionPerformed

    private void tgl_contact2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tgl_contact2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_contact2ItemStateChanged

    private void tgl_contact2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgl_contact2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_contact2MouseEntered

    private void tgl_contact2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgl_contact2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_contact2MouseExited

    private void tgl_contact2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_contact2ActionPerformed
        // TODO add your handling code here:
        int dialogresult = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to abort the transaction, Click Yes to Print", "Hello Print", JOptionPane.YES_OPTION);;
            if (dialogresult == 0){
                this.dispose();
            }
       
    }//GEN-LAST:event_tgl_contact2ActionPerformed

    private void txt_poidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_poidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_poidKeyTyped

    private void txt_dateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateKeyTyped

    private void txt_supid3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_supid3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_supid3KeyTyped

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Navigation1;
    private javax.swing.JCheckBox checkbox1;
    private javax.swing.JComboBox cmbSup;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lbl_medical1;
    public static javax.swing.JTable order_table;
    private javax.swing.JToggleButton tgl_basic2;
    private javax.swing.JToggleButton tgl_contact2;
    private javax.swing.JToggleButton tgl_genOrder;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_poid;
    private javax.swing.JTextField txt_supid3;
    // End of variables declaration//GEN-END:variables
}
