/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms;

import static cms.function.Loginfunction.Firstname;
import static cms.function.Loginfunction.Lastname;
import cms.function.SQLConnection;
import static cms.function.UI_function.hello;
import static cms.function.tbl_function.tbl_function;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Paint;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import org.apache.commons.lang.WordUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.StackedBarRenderer3D;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Benjie
 */
public class show_comp extends javax.swing.JDialog {
    
    Connection conn = SQLConnection.ConnDB();
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    Statement st = null;

    /**
     * Creates new form show_comp
     */
    public show_comp() {
        initComponents();
        hello();
        tbl_function(tbl_comp);
        for(int years = 2015 ; years<=Calendar.getInstance().get(Calendar.YEAR);years++){
                //years_tmp.add(years+"");
                cmb_taon.addItem(years);
                cmb_taon1.addItem(years);
                
        }
        int last = cmb_taon.getItemCount()-1;
        cmb_taon.setSelectedIndex(last);
        
        int last1 = cmb_taon1.getItemCount()-1;
        cmb_taon1.setSelectedIndex(last);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        cmb_taon = new javax.swing.JComboBox();
        jLabel111 = new javax.swing.JLabel();
        cmb_buwan = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_comp = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        printResultBut = new javax.swing.JButton();
        graphToGago = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        cmb_taon1 = new javax.swing.JComboBox();
        jLabel113 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 61, 115)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(10, 61, 115)));

        jLabel112.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(46, 47, 51));
        jLabel112.setText("Year");

        cmb_taon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_taon.setForeground(new java.awt.Color(40, 40, 30));
        cmb_taon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_taonItemStateChanged(evt);
            }
        });

        jLabel111.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(46, 47, 51));
        jLabel111.setText("Month");

        cmb_buwan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_buwan.setForeground(new java.awt.Color(40, 40, 30));
        cmb_buwan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmb_buwan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_buwanItemStateChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl_comp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbl_comp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "ID Number", "Fullname", "Illness", "Medication (Count)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_comp.setRowHeight(27);
        tbl_comp.setRowMargin(5);
        tbl_comp.setShowHorizontalLines(false);
        tbl_comp.setShowVerticalLines(false);
        tbl_comp.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_comp);

        jPanel2.setBackground(new java.awt.Color(10, 61, 115));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Comprehensive Report");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        printResultBut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        printResultBut.setText("Print Result");
        printResultBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printResultButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graphToGagoLayout = new javax.swing.GroupLayout(graphToGago);
        graphToGago.setLayout(graphToGagoLayout);
        graphToGagoLayout.setHorizontalGroup(
            graphToGagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphToGagoLayout.setVerticalGroup(
            graphToGagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Show Graph");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "College", "Senior High", "Employee Staff", "Visitors"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 61, 115));
        jLabel3.setText("TOTAL NUMBER DISPENSE TO COLLEGE :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(10, 61, 115));
        jLabel4.setText("TOTAL NUMBER DISPENSE TO SENIOR HIGH :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(10, 61, 115));
        jLabel5.setText("TOTAL NUMBER DISPENSE TO VISITORS :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(10, 61, 115));
        jLabel6.setText("TOTAL NUMBER DISPENSE TO EMPLOYEE/STAFF :");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(10, 61, 115));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(10, 61, 115));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(10, 61, 115));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(10, 61, 115));

        cmb_taon1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_taon1.setForeground(new java.awt.Color(40, 40, 30));
        cmb_taon1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_taon1ItemStateChanged(evt);
            }
        });

        jLabel113.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(46, 47, 51));
        jLabel113.setText(" Year :");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 461, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_taon1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_taon1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel113)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Medicine Dispense Reports", jPanel4);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "Medicine/Supply Dispense", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patient Reports", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmb_taon, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmb_buwan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(67, 67, 67)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(printResultBut, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(graphToGago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel112)
                    .addComponent(cmb_taon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel111)
                    .addComponent(cmb_buwan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(printResultBut, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphToGago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_taonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_taonItemStateChanged

    }//GEN-LAST:event_cmb_taonItemStateChanged

    private void cmb_buwanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_buwanItemStateChanged

    }//GEN-LAST:event_cmb_buwanItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String month = cmb_buwan.getSelectedItem().toString();
            String year = cmb_taon.getSelectedItem().toString();
            int i = 0;

            String ya = "";
        
            DefaultTableModel mod = (DefaultTableModel)tbl_comp.getModel();
            mod.setRowCount(0);
            
            String comp = "SELECT TIME_FORMAT(a.time, '%h:%i %p') AS 'Time', a.id_no, DATE_FORMAT(a.date_given, '%M %e %Y') x, b.med_name y, c.ill_name a, NULLIF (COUNT(a.med_id),0)z, a.amount abaka, d.lastname, d.firstname, d.middlename "
                        + " FROM med_dspnsd a LEFT JOIN med_table b"
                        + " ON a.med_id = b.med_id"
                        + " INNER JOIN ill_table c"
                        + " ON a.ill_id = c.ill_id"
                        + " INNER JOIN patient_tbl d"
                        + " ON a.id_no = d.id_no"
                        + " WHERE DATE_FORMAT(date_given,'%M') = '"+month+"' AND DATE_FORMAT(date_given, '%Y') = '"+year+"'"
                        + " GROUP BY b.med_name, a.date_given, d.id_no, a.time"
                        + " ORDER BY a.date_given, a.time";
            
            pstmt = conn.prepareStatement(comp);
            rs = pstmt.executeQuery();
            while (rs.next()){
                String date = rs.getString("x");  
                String purpose = rs.getString("a"); //illness
                String name = rs.getString("y"); //medname
                if (name==null){
                    name = " - ";
                }
                int acount = rs.getInt("z"); //count
                int abaka = rs.getInt("abaka"); //amount
                String last = rs.getString("d.lastname");
                String first = rs.getString("d.firstname");
                String mid = rs.getString("d.middlename");
                String id = rs.getString("a.id_no");
                String time = rs.getString("Time");
                
                String lastnato = WordUtils.capitalizeFully(last)+", "+WordUtils.capitalize(first)+" "+WordUtils.capitalizeFully(WordUtils.initials(mid)+".");

                int po = (acount * abaka);
                

                mod.addRow(new Object[]{date,time,id,lastnato, purpose,name+"  ("+po+")"});   
                i = i + po;

            }
            int kalo = 0;
            String yush = "SELECT DISTINCT(COUNT(id_no)) opo FROM med_dspnsd"
                    + " WHERE DATE_FORMAT(date_given,'%M') = '"+month+"' AND DATE_FORMAT(date_given, '%Y') = '"+year+"'"
                    + " GROUP BY id_no";
            pstmt = conn.prepareStatement(yush);
            rs = pstmt.executeQuery();
            while (rs.next()){
                
                int opo = rs.getInt("opo");
                kalo = kalo + opo;
                
            
            }
            mod.addRow(new Object[]{"","","","","",""});
            mod.addRow(new Object[]{"","","","","",""});
            mod.addRow(new Object[]{"TOTAL PATIENT: ",kalo, "","","",""});
            mod.addRow(new Object[]{"NO. OF MEDICINE DISPENSED: ",i,"","","",""});
                
               
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void printResultButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printResultButActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel) tbl_comp.getModel();
        JRTableModelDataSource  datasource = new JRTableModelDataSource(mod);
        String reportSource = "C:\\Users\\Benjie\\Desktop\\PROGRAM FILE THESIS 2015-2016\\CMS\\CMS\\src\\reports\\compreReports.jrxml";
        
        int x = mod.getRowCount();
        String year = cmb_taon.getSelectedItem().toString();
        String month = cmb_buwan.getSelectedItem().toString();
        String nurseName = Firstname +" "+ Lastname;

        if (x == 0){
                JOptionPane.showMessageDialog(this, "No result to be print");
        }else{
            try {
                JasperReport jr =  JasperCompileManager.compileReport(reportSource);
                Map<String, Object> params = new HashMap<String, Object>();
                params.put("year", year);
                params.put("month", month);
                params.put("nurseName", nurseName);
                JasperPrint jp = JasperFillManager.fillReport(jr, params, datasource);
                JasperPrintManager.printReport(jp, false);

                JasperExportManager.exportReportToPdfFile(jp,"report.pdf");
                if (Desktop.isDesktopSupported()) {
                    try {
                        File myFile = new File("report.pdf");
                        Desktop.getDesktop().open(myFile);
                    } catch (IOException ex) {
                        // no application registered for PDFs
                    }
                }

            } catch (JRException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_printResultButActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] totalDate = new String[12];
        try {
              
            String query = "SELECT DATE_FORMAT(date_given, '%M'), SUM(amount) FROM med_dspnsd WHERE DATE_FORMAT(date_given, '%Y') = '"+cmb_taon.getSelectedItem().toString()+"' GROUP BY DATE_FORMAT(date_given, '%M') ORDER BY date_given";
            JDBCCategoryDataset dataset  = new JDBCCategoryDataset(SQLConnection.ConnDB(), query);
            
            JFreeChart chart = ChartFactory.createLineChart("", "","", dataset, PlotOrientation.VERTICAL,
                false, false, false);
            chart.setBackgroundPaint(Color.WHITE); // Set the background colour of the chart
            chart.getTitle().setPaint(Color.WHITE); // Adjust the colour of the title
            chart.setBorderPaint(Color.BLUE);
            
            
            CategoryPlot p = chart.getCategoryPlot(); // Get the Plot object for a bar graph
            p.setBackgroundPaint(Color.WHITE); // Modify the plot background
            p.setRangeGridlinePaint(Color.BLUE);
            
             
            //DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//            dataset.setValue(Double.parseDouble(totalDate[0]), "Profit", "Jan");
//            dataset.setValue(Double.parseDouble(totalDate[1]), "Profit", "Feb");
//            dataset.setValue(Double.parseDouble(totalDate[2]), "Profit", "Mar");
//            dataset.setValue(Double.parseDouble(totalDate[3]), "Profit", "Apr");
//            dataset.setValue(Double.parseDouble(totalDate[4]), "Profit", "May");
//            dataset.setValue(Double.parseDouble(totalDate[5]), "Profit", "Jun");
//            dataset.setValue(Double.parseDouble(totalDate[6]), "Profit", "Jul");
//            dataset.setValue(Double.parseDouble(totalDate[7]), "Profit", "Aug");
//            dataset.setValue(Double.parseDouble(totalDate[8]), "Profit", "Sep");
//            dataset.setValue(Double.parseDouble(totalDate[9]), "Profit", "Oct");
//            dataset.setValue(Double.parseDouble(totalDate[10]), "Profit", "Nov");
//            dataset.setValue(Double.parseDouble(totalDate[11]), "Profit", "Dec");
            
            ChartPanel ps = new ChartPanel(chart);
            ps.setMouseZoomable(false);
            graphToGago.add(ps);
            ps.setSize(graphToGago.getWidth(), graphToGago.getHeight());
            ps.setVisible(true);

            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "showGraphPie");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void cmb_taon1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_taon1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_taon1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try {
            st = conn.createStatement();
            String query = "SELECT DATE_FORMAT(date_given, '%M') AS month, SUM(amount) AS count FROM med_dspnsd WHERE DATE_FORMAT(date_given, '%Y') = '"+cmb_taon1.getSelectedItem().toString()+"' GROUP BY DATE_FORMAT(date_given, '%M') ORDER BY date_given;";
            rs = st.executeQuery(query);

            while (rs.next()){
                String month = rs.getString("month");
                String count = rs.getString("count");
                
                model.addRow(new Object[]{month, count});
            }

        } catch (SQLException e) {
            e.printStackTrace();
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        hello();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show_comp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_buwan;
    private javax.swing.JComboBox cmb_taon;
    private javax.swing.JComboBox cmb_taon1;
    private javax.swing.JPanel graphToGago;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton printResultBut;
    private javax.swing.JTable tbl_comp;
    // End of variables declaration//GEN-END:variables
}
